QuanlySach/BookStore/Models/NhaXuatBan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXuatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}

QuanlySach/BookStore/Controllers/NhaXuatBanController.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class NhaXuatBanController : Controller
    {
        //Db :
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: NhaXuatBan
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult NhaXuatBanPartial()
        {
            return PartialView(db.NhaXuatBans.OrderBy(n => n.TenNXB).ToList());
        }
        public ViewResult SachTheoNhaXuatBan(int Ma = 0)
        {
            NhaXuatBan nxb = db.NhaXuatBans.SingleOrDefault(n => n.MaNXB == Ma);
            if (nxb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Sach> sach = db.Saches.Where(n => n.MaNXB == Ma).OrderBy(n => n.GiaBan).ToList();
            if (sach.Count == 0)
            {
                ViewBag.Sach = "Không có Cuốn Sách Nào thuộc Nhà Xuất Bản Này!.";
                return null;
            }
            return View(sach);

        }
        public ViewResult DanhMucNhaXuatBan()
        {
            return View(db.NhaXuatBans.ToList());
        }
    }
}

QuanlySach/BookStore/Controllers/SachController.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class SachController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: Sach
        public ActionResult Index()
        {
            return View();
        }
        //List danh sach :
        public ActionResult DanhsachSach()
        {
            return View(db.Saches.ToList());
        }

        public PartialViewResult SachMoiPartial()
        {
            var ListSachMoi = db.Saches.Take(3).ToList();
            return PartialView(ListSachMoi);
        }
        public ViewResult XemChiTiet(int Ma = 0)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == Ma);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
    }
}

QuanlySach/BookStore/Views/NhaXuatBan/DanhMucNhaXuatBan.cshtml
@using BookStore.Models;
@model List<NhaXuatBan>
@{
    ViewBag.Title = "DanhMucNhaXuatBan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh Mục Nhà Xuất Bản</h2>

@foreach (var item in Model)
{
    <a href="@Url.Action("SachTheoNhaXuatBan","NhaXuatBan",new {@Ma=item.MaNXB})" class="button button-submit">@item.TenNXB</a>
}

QuanlySach/BookStore/Views/NhaXuatBan/NhaXuatBanPartial.cshtml
@using BookStore.Models;
@model List<NhaXuatBan>

<h2 style="color:red;background:#ccc;padding:15px 0;text-align:center;">Danh sách nhà xuất bản : </h2>
@{
    foreach (var item in Model)
    {
        <a href="@Url.Action("SachTheoNhaXuatBan","NhaXuatBan",new { @Ma=item.MaNXB})" class="button button-submit">@item.TenNXB</a>
    }
}
<br />

QuanlySach/BookStore/Views/NhaXuatBan/SachTheoNhaXuatBan.cshtml
@using BookStore.Models;
@model List<Sach>
@{
    ViewBag.Title = "SachTheoNhaXuatBan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Sách Theo Nhà Xuất Bản</h2>
@if (Model.Count == 0)
{
    <h1>@ViewBag.Sach</h1>
}

@{ int i = 0;}
@foreach (var item in Model)
{
    i++;
    <div class="sanpham" style="float:left;text-align:center; margin:0 4%">
        <a href="@Url.Action("XemChiTiet","Sach",new { @Ma=item.MaSach})"><img src="~/HinhAnhSP/@item.AnhBia" alt="Image" style="width:150px;height:150px;" /></a><br />
        @if (item.TenSach.Length < 20)
        {
            <div class="tenSach" style="float:left;color:#000;font-weight:bold "><strong>Tên Sách:</strong> @item.TenSach</div><br />
        }
        else
        {
            <div class="tenSach" style="float:left;color:#000;font-weight:bold"><strong>Tên Sách:</strong>@item.TenSach.Substring(0, 20) ... </div><br />
        }
        <div class="gia" style="float:left;color:red;font-size:20px;font-weight:bold"><strong>Gía:</strong>@string.Format("{0:0,0}", item.GiaBan) <strong>vnd</strong></div><br />
    </div>
    if (i % 3 == 0)
    {
        <hr />
    }
}
<div style="clear:both"></div>