QuanlySach/BookStore/Models/ChuDe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuDe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuDe()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaChuDe { get; set; }
        public string TenChuDe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}

QuanlySach/BookStore/Controllers/AdminController.cs
using BookStore.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class AdminController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: Admin
        // Index Sach :
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;

            return View(db.Saches.ToList().OrderBy(n => n.MaSach).ToPagedList(pageNum, pageSize));
        }
        //Index DatHang :
        public ActionResult IndexDH(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;

            return View(db.DonHangs.ToList().OrderBy(n => n.MaKH).ToPagedList(pageNum, pageSize));
        }
        //Index ChiTietDonHang :
        public ActionResult IndexCTDH(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;

            return View(db.ChiTietDonHangs.ToList().OrderBy(n => n.MaDonHang).ToPagedList(pageNum, pageSize));
        }

        // Get add sach
        [HttpGet]
        public ActionResult ThemMoi()
        {
            ViewBag.MachuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            return View();
        }
        /*
        [HttpPost]
        public ActionResult ThemMoi(Sach sach,HttpPostedFileBase  fileUpload)
        {
            //luu ten cua file.

            var fileName = Path.GetFileName(fileUpload.FileName);

            //luu duong dan cua file.
            var path = Path.Combine(Server.MapPath("~/HinhAnhSP"),fileName);

            if (System.IO.File.Exists(path))
            {
               ViewBag.ThongBao = "Hình Ảnh đã tồn tại.";
            }
            else
            {
                fileUpload.SaveAs(path);
            }
            ViewBag.MachuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

            return View();
        }
        */
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(Sach sach, HttpPostedFileBase fileUpload)
        {


            //dua du lieu vao dropdowlist.
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

            //kiem tra duong dan anh bia.
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }

            //them vao co so du lieu.
            if (ModelState.IsValid)
            {
                //luu ten cua file.
                var fileName = Path.GetFileName(fileUpload.FileName);
                //luu duong dan cua file.
                var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                //kiem tra hinh anh da ton tai chua.
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;
                db.Saches.Add(sach);
                db.SaveChanges();
            }
            return View();

        }

        //Get edit sach :
        [HttpGet]
        public ActionResult ChinhSua(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Sach sach, FormCollection f)
        {         
            if (ModelState.IsValid)
            {
                //cập nhật.
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return RedirectToAction("Index");
        }

        // Hien thi 
        public ActionResult HienThi(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }

        //Get sach :
        [HttpGet]
        public ActionResult Xoa(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost]
        [ActionName("Xóa")]
        public ActionResult XacNhanXoa(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

QuanlySach/BookStore/Controllers/ChuDeController.cs
using BookStore.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class ChuDeController : Controller
    {
        //db :
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: ChuDe
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;
            return View(db.ChuDes.ToList().OrderBy(n => n.MaChuDe).ToPagedList(pageNum, pageSize));
        }
        public PartialViewResult ChuDePartial()
        {
            return PartialView(db.ChuDes.Take(5).ToList());
        }
        public ViewResult SachTheoChuDe(int Ma = 0)
        {
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == Ma);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Sach> sach = db.Saches.Where(n => n.MaChuDe == Ma).OrderBy(n => n.GiaBan).ToList();
            if (sach.Count == 0)
            {
                ViewBag.Sach = "Không Có Sách Nào Thuộc Chủ Đề Này";
            }
            return View(sach);
        }
        public ViewResult DanhMucChuDe()
        {
            return View(db.ChuDes.ToList());
        }

        //CRUD chu de :
        //Add chu de 
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(ChuDe chude)
        {        
            if (ModelState.IsValid)
            {                           
                db.ChuDes.Add(chude);
                db.SaveChanges();
            }
            return View();
        }

    }
}

QuanlySach/BookStore/Controllers/SachController.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class SachController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: Sach
        public ActionResult Index()
        {
            return View();
        }
        //List danh sach :
        public ActionResult DanhsachSach()
        {
            return View(db.Saches.ToList());
        }

        public PartialViewResult SachMoiPartial()
        {
            var ListSachMoi = db.Saches.Take(3).ToList();
            return PartialView(ListSachMoi);
        }
        public ViewResult XemChiTiet(int Ma = 0)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == Ma);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
    }
}

QuanlySach/BookStore/Views/ChuDe/ChuDePartial.cshtml
@using BookStore.Models;
@model List<ChuDe>

<h2 style="color:red;background:#ccc;padding:15px 0;text-align:center;">Danh sách chủ đề : </h2>
@{
    foreach (var item in Model)
    {
        <a href="@Url.Action("SachTheoChuDe","ChuDe",new { @Ma=item.MaChuDe})" class="button button-submit">@item.TenChuDe</a>
    }
}
<br />

QuanlySach/BookStore/Views/ChuDe/DanhMucChuDe.cshtml
@using BookStore.Models;
@model List<ChuDe>
@{
    ViewBag.Title = "DanhMucChuDe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh Mục Chủ Đề</h2>

@foreach (var item in Model)
{
    <a href="@Url.Action("SachTheoChuDe","ChuDe", new { @Ma=item.MaChuDe})" class="button button-delete">@item.TenChuDe</a>
}

QuanlySach/BookStore/Views/ChuDe/Index.cshtml
@using BookStore.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<BookStore.Models.ChuDe>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin.cshtml";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Thêm Mới", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>          
        <th>
            @Html.DisplayNameFor(model => model.First().TenChuDe)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaChuDe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenChuDe)
            </td>           
            <td>
                @Html.ActionLink("Chỉnh Sửa", "ChinhSua", new { @MaSach = item.MaChuDe}) |;
                @Html.ActionLink("Chi tiết", "HienThi", new { @MaSach = item.MaChuDe }) |
                @Html.ActionLink("Xóa", "Xoa", new { @MaSach = item.MaChuDe })
            </td>
        </tr>
    }

</table>

@*Tạo page trang*@
Trang @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
@Html.PagedListPager(Model, page => Url.Action("index", "Admin", new { page = page })).

QuanlySach/BookStore/Views/ChuDe/SachTheoChuDe.cshtml
@using BookStore.Models;
@model List<Sach>

@{
    ViewBag.Title = "SachTheoChuDe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:red;font-weight:bold">Sách Theo Chủ Đề</h2>
@if (Model.Count == 0)
{
    <h1>@ViewBag.Sach</h1>
}

@{ int i = 0;}
@foreach (var item in Model)
{
    i++;
<div class="sanpham" style="float: left; text-align: center; margin: 30px 30px 40px 50px">
    <a href="@Url.Action("XemChiTiet","Sach",new { @Ma=item.MaSach})"><img src="~/HinhAnhSP/@item.AnhBia" alt="Image" style="width:125px;height:150px;" /></a><br />
    @if (item.TenSach.Length > 10)
    {
        <div class="tenSach" style="float: left; color: #000; font-weight: bold; font-size: 10px; text-align: center "> @item.TenSach</div><br />
    }
    else
    {
        <div class="tenSach" style="float:left;color:#000;font-weight:bold;font-size:5px"> @item.TenSach.Substring(0, 10) ... </div><br />
    }
    <div class="gia" style="float:left;color:red;font-size:15px;font-weight:bold"><strong> Giá : </strong>@string.Format("{0:0,0}", item.GiaBan) <strong>vnd</strong></div><br />
    @using (Html.BeginForm("ThemGioHang", "GioHang", new { @Ma = item.MaSach, @strURL = Request.Url.ToString() }))
    {
        <button type="submit" class="button button-delete" style="margin-top:1%"> Mua Hàng <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
    }
</div>
    if (i % 4 == 0)
    {
        <hr />
    }
}
<div style="clear:both"></div>

QuanlySach/BookStore/Views/ChuDe/ThemMoi.cshtml
@model BookStore.Models.ChuDe
@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Shared/Admin.cshtml";
}

<h2>ThemMoi</h2>
@using (Html.BeginForm("ThemMoi", "Chude", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChuDe, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>