QuanlySach/BookStore/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
        // Gioi Thieu
        public ActionResult GioiThieu()
        {
            return View();
        }
        //Lien He
        public ActionResult LienHe()
        {
            return View();
        }
        // Tin tuc :
        public ActionResult TinTuc()
        {
            return View();
        }

    }
}

QuanlySach/BookStore/Controllers/AdminController.cs
using BookStore.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class AdminController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: Admin
        // Index Sach :
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;

            return View(db.Saches.ToList().OrderBy(n => n.MaSach).ToPagedList(pageNum, pageSize));
        }
        //Index DatHang :
        public ActionResult IndexDH(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;

            return View(db.DonHangs.ToList().OrderBy(n => n.MaKH).ToPagedList(pageNum, pageSize));
        }
        //Index ChiTietDonHang :
        public ActionResult IndexCTDH(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;

            return View(db.ChiTietDonHangs.ToList().OrderBy(n => n.MaDonHang).ToPagedList(pageNum, pageSize));
        }

        // Get add sach
        [HttpGet]
        public ActionResult ThemMoi()
        {
            ViewBag.MachuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            return View();
        }
        /*
        [HttpPost]
        public ActionResult ThemMoi(Sach sach,HttpPostedFileBase  fileUpload)
        {
            //luu ten cua file.

            var fileName = Path.GetFileName(fileUpload.FileName);

            //luu duong dan cua file.
            var path = Path.Combine(Server.MapPath("~/HinhAnhSP"),fileName);

            if (System.IO.File.Exists(path))
            {
               ViewBag.ThongBao = "Hình Ảnh đã tồn tại.";
            }
            else
            {
                fileUpload.SaveAs(path);
            }
            ViewBag.MachuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

            return View();
        }
        */
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(Sach sach, HttpPostedFileBase fileUpload)
        {


            //dua du lieu vao dropdowlist.
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

            //kiem tra duong dan anh bia.
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }

            //them vao co so du lieu.
            if (ModelState.IsValid)
            {
                //luu ten cua file.
                var fileName = Path.GetFileName(fileUpload.FileName);
                //luu duong dan cua file.
                var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                //kiem tra hinh anh da ton tai chua.
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;
                db.Saches.Add(sach);
                db.SaveChanges();
            }
            return View();

        }

        //Get edit sach :
        [HttpGet]
        public ActionResult ChinhSua(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Sach sach, FormCollection f)
        {         
            if (ModelState.IsValid)
            {
                //cập nhật.
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            return RedirectToAction("Index");
        }

        // Hien thi 
        public ActionResult HienThi(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }

        //Get sach :
        [HttpGet]
        public ActionResult Xoa(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost]
        [ActionName("Xóa")]
        public ActionResult XacNhanXoa(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

QuanlySach/BookStore/Controllers/SachController.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class SachController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: Sach
        public ActionResult Index()
        {
            return View();
        }
        //List danh sach :
        public ActionResult DanhsachSach()
        {
            return View(db.Saches.ToList());
        }

        public PartialViewResult SachMoiPartial()
        {
            var ListSachMoi = db.Saches.Take(3).ToList();
            return PartialView(ListSachMoi);
        }
        public ViewResult XemChiTiet(int Ma = 0)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == Ma);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
    }
}

QuanlySach/BookStore/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;

namespace BookStore.Controllers
{
    public class TimKiemController : Controller
    {
        QuanLiBanSachEntities db = new QuanLiBanSachEntities();
        // GET: TimKiem
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f, int? page)
        {
            //lay tu khoa nhap vao roi tim kiem ben trong co so du lieu.

            string tukhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = tukhoa;
            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(tukhoa)).ToList();
            //phan trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Khong tim thay san pham nao";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Da tim thay " + lstKQTK.Count + " San pham.";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult KetQuaTimKiem(string tukhoa, int? page)
        {
            //lay tu khoa nhap vao roi tim kiem ben trong co so du lieu.
            ViewBag.TuKhoa = tukhoa;

            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(tukhoa)).ToList();
            //phan trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Khong tim thay san pham nao";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Da tim thay " + lstKQTK.Count + " San pham.";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
    }
}

QuanlySach/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ô-tô</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/screen.css" rel="stylesheet" />
    <link href="~/Content/fonts.css" rel="stylesheet" />
    <link href="~/Content/css.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/nivo-slider.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.nivo.slider.js"></script>
</head>
<body>
    @*P_1*@
    <section class="blank">
        @* P_1.1 *@
        <div class="flash">
            <div class="phone">
                <i class="fa fa-mobile" aria-hidden="true"></i>Liên hệ:12345xxx
            </div>
            <div class="dangki_dangnhap">
                @Html.Action("GioHangPartial", "GioHang")
                <i class="" aria-hidden="true" target="_blank"></i>@Html.ActionLink("Đăng Kí", "DangKi", "NguoiDung", null, htmlAttributes: new { @class = "DangKi" })
                <i class="" aria-hidden="true" target="_blank"></i>@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung", null, htmlAttributes: new { @class = "DangNhap" })
                <i class="" aria-hidden="true" target="_blank"></i>@Html.ActionLink("Trang Quản Trị","Index", "Admin", null, htmlAttributes: new { @class = "DangNhap" })
            </div>
        </div>
        @*p_1.2 *@
        <div class="flash success" style="background-color:forestgreen">
            <div class="timkiem">
                @using (Html.BeginForm("KetQuaTimKiem", "TimKiem", FormMethod.Post))
                {
                    @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Nhập Vào Từ Tìm Kiếm " })
                    <button class="btntimkiem" type="submit"></button>
                }
            </div>
            <div class="menu-top">
                <ul>
                    <li><a href="@Url.Action("Index","Home")"> Trang Chủ</a></li>
                    <li><a href="@Url.Action("GioiThieu","Home")"> Giới Thiệu</a></li>
                    <li><a href="@Url.Action("Index","Home")"> Sách</a></li>
                    <li><a href="@Url.Action("TinTuc","About")"> Tin Tức</a></li>
                    <li><a href="@Url.Action("LienHe","About")"> Liên Hệ</a></li>
                </ul>
            </div>
        </div>
    </section>
    @* P_2*@
    <section style="height:500px">
        @*@Html.Action("SachMoiPartial", "Sach")*@
        <div class="slider" style="height:400px">
            <div id="slider" class="nivoSlider">
                <img src="../hinhanh/1_1.jpg" data-thumb="images/toystory.jpg" alt="" data-transition="slideInLeft" />
                <img src="../hinhanh/1_2.jfif" data-thumb="images/up.jpg" alt="" title="" />
                <img src="../hinhanh/1_3.jpg" data-thumb="images/walle.jpg" alt="" data-transition="slideInLeft" />
                <img src="../hinhanh/1_4.jfif" data-thumb="images/nemo.jpg" alt="" title="" />
                <img src="../hinhanh/1_5.png" data-thumb="images/nemo.jpg" alt="" data-transition="slideInLeft"  title="" />
            </div>
        </div>       
    </section>

    <section>
        <div>
            <div>             
                <div>
                    Tủ sách Giáo dục Đại học tập hợp những cuốn sách giới thiệu về  những mô hình và hướng phát triển Đại học của các nước có nền giáo dục phát triển, hướng đến việc xây dựng đại học trở thành nơi không chỉ là trung tâm đào tạo nhân tài, mà còn là một trung tâm khoa học và văn hóa, với tự do học thuật được xem là đặc điểm quan trọng nhất.  Đại học là nơi mà các thành viên (giáo sư, giảng viên, sinh viên) tự do theo đuổi đề tài nghiên cứu, tự do giảng dạy, tự do học để đi tìm sự thật (chân lí).v
                </div>
                <br />
                <hr />
            </div>
        </div>
        <div class="noidung" style="margin:1px 1px 1px 1px">
            @RenderBody()
        </div>
    </section>
    <section>
        <script src="~/Scripts/js-jquery.js"></script>
        <div class="content ">
            <div class="container">
                <div >
                    <h2> Bản đồ :</h2>
                    <hr/>
                    <div >
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.3542455613465!2d105.77976975168298!3d21.05850910620527!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab2aba129325%3A0x1f72e665dbc0db5b!2zNDMgQ-G7lSBOaHXhur8sIEPhu5UgTmh14bq_IDEsIFThu6sgTGnDqm0sIEjDoCBO4buZaSwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1484555866770" width="1100" height="500" frameborder="0" style="border:5px" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="footer" style="">
            <div class="end">
                <div class="container">
                    <div class="col-md-4">
                        <div class="footer_container">
                            <h3>Cửa hàng bán bán Giày </h3>
                            <p style="background: url(images/loca.png) no-repeat left center">Địa chỉ: Cô lô nhuê - Bắc Từ Liêm - Hà Nội</p>
                            <p style="background: url(images/phone.png) no-repeat left center">Điện thoại:0358845050 </p>
                            <p style="background: url(images/mail.png) no-repeat left center">Email: duongnm110198@gmail.com</p>                         
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="footer_container">
                            <h3>QUY ĐỊNH & CHÍNH SÁCH</h3>
                            <p><a href="#" style="color: #a7a7a7">QĐ đổi hàng và hoàn trả tiền</a></p>
                            <p><a href="#" style="color: #a7a7a7">Quy Định</a></p>
                            <p><a href="#" style="color: #a7a7a7">Chính sách cửa hàng</a></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="footer_container">
                            <h3>Hỗ trợ online</h3>
                            <div style="line-height: 31px; color: white;">
                                <span>Số người đang Online:</span>
                                <asp:Label ID="lblsonguoiOnline" runat="server" Text=""></asp:Label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <a href="#" class="button button-buy">Minh Dương&copy;2021 </a>
        </div>
    </section>
</body>

<script type="text/javascript">
    $(window).load(function () {
        $('#slider').nivoSlider({
        });
    });
</script>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1838823719729580";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

</html>